[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    moononournation/GFX Library for Arduino @ ^1.4.7
    https://github.com/h2zero/NimBLE-Arduino.git
    https://github.com/wakwak-koba/ESP32-NimBLE-Mouse.git
